# moonfish is licensed under the AGPL (v3 or later)
# copyright 2023 zamfofex

image: alpine/latest
packages:
  - build-base
  - bearssl-dev
  - xz
sources:
  - https://git.sr.ht/~zamfofex/moonfish
  - https://github.com/DaveGamble/cJSON#v1.7.16
tasks:
  - build-cjson: |
      cd cJSON
      make
      mkdir cjson
      mv cJSON.h cjson
  - build: |
      cd moonfish
      make CPPFLAGS=-I../cJSON LDFLAGS='-static -L../cJSON'
  - minify: |
      cd moonfish
      ./minify.sh
artifacts:
  - moonfish/moonfish
  - moonfish/play
  - moonfish/lichess
  - moonfish/analyse
  - moonfish/moonfish.sh
